// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OMAPGServiceData.Models;
using System;

namespace OMAPGService.Migrations
{
    [DbContext(typeof(OMAPGContext))]
    [Migration("20171017015348_addServiceData")]
    partial class addServiceData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("OMAPGServiceData.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceId");

                    b.Property<int>("OSType");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("OMAPGServiceData.Models.Gym", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<string>("description");

                    b.Property<bool>("is_in_battle");

                    b.Property<long>("last_modified");

                    b.Property<double>("lat");

                    b.Property<double>("lon");

                    b.Property<string>("name");

                    b.Property<int>("pokemon_id");

                    b.Property<string>("pokemon_name");

                    b.Property<int>("sigting_id");

                    b.Property<int?>("slots_available");

                    b.Property<int>("team");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("OMAPGServiceData.Models.Pokemon", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<int>("atk");

                    b.Property<int>("cp");

                    b.Property<string>("damage1");

                    b.Property<string>("damage2");

                    b.Property<int>("def");

                    b.Property<int>("gender");

                    b.Property<double>("lat");

                    b.Property<int>("level");

                    b.Property<double>("lon");

                    b.Property<string>("move1");

                    b.Property<string>("move2");

                    b.Property<string>("name");

                    b.Property<int>("pokemon_id");

                    b.Property<int>("sta");

                    b.Property<bool>("trash");

                    b.HasKey("id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("OMAPGServiceData.Models.Raid", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<int>("cp");

                    b.Property<double>("lat");

                    b.Property<int>("level");

                    b.Property<double>("lon");

                    b.Property<string>("move_1");

                    b.Property<string>("move_2");

                    b.Property<string>("name");

                    b.Property<int>("pokemon_id");

                    b.Property<string>("pokemon_name");

                    b.Property<int>("team");

                    b.HasKey("id");

                    b.ToTable("Raids");
                });
#pragma warning restore 612, 618
        }
    }
}
